#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/dbus-1/system.d/NetworkManager.conf /etc/dbus-1/system.d/org.freedesktop.NetworkManager.conf 0.9.4.0-1~ network-manager -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/network-manager" ] && [ "$1" = remove ]; then
	invoke-rc.d network-manager stop || exit $?
fi
# End automatically added section
