#!/bin/sh

set -e

case "$1" in
 install|upgrade)
  #removing old backup
  rm -fr /boot/config.txt.2013*
  rm -fr /boot/cmdline.txt.2013*
  rm -fr /boot/backup2013*.tar
  # Backup old config.txt & cmdline.txt
  mv /boot/config.txt /boot/config.txt.$(date +%Y%m%d)
  mv /boot/cmdline.txt /boot/cmdline.txt.$(date +%Y%m%d)
  tar cvf /boot/backup$(date +%Y%m%d).tar /boot/*.bin /boot/*.elf /boot/*.dat
  rm -fr /boot/*.bin /boot/*.elf /boot/*.dat
 ;;
 abort-upgrade)
 ;;
 *)
  exit 1
 ;;
esac
