#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/wicd" ] && [ "$1" = remove ]; then
	invoke-rc.d wicd stop || exit $?
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p wicd-daemon 
else
	dpkg -L wicd-daemon | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
